Repository silverstripe/silverstripe-tagfield, pull requests merged in 2019-02, with the labels that each got.

#128 Update faulty import of TagField component
  client/src/boot/registerComponents.js
Labels: affects/v4, change/patch, feedback-required/author

#135 Update readme.md
  readme.md
Labels: affects/v4, type/docs

#136 Component TagField does not exist (Proptypes Issue)
  client/dist/js/bundle.js
  client/src/components/TagField.js
  package.json
  yarn.lock
Labels: affects/v4, change/patch

#137 FIX StringTagField now works with SS-2018-021/CVE-2019-5715 by serialising arrays before write
  src/StringTagField.php
Labels: affects/v4, change/patch

#138 FIX StringTagField now works with SS-2018-021/CVE-2019-5715 by serialising arrays before write
  code/StringTagField.php
Labels: affects/v3, change/patch
